<a href="https://colab.research.google.com/github/santhosh1728/FML/blob/main/Copy_of_ML_CODE_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
df=pd.DataFrame([[1.0,2.0,3.0,4.0],[12.2,2.3,4.3,2.3],[np.NaN,3,4,2]])
df.columns=['A','B','C','D']
print(df)
print(df.isnull().sum())

      A    B    C    D
0   1.0  2.0  3.0  4.0
1  12.2  2.3  4.3  2.3
2   NaN  3.0  4.0  2.0
A    1
B    0
C    0
D    0
dtype: int64


In [10]:
df=pd.DataFrame([[1.0,2.0,3.0,4.0],[12.2,2.3,4.3,2.3],[np.NaN,3,4,np.NaN]])
df.columns=['A','B','C','D']
print(df)
print(df.isnull().sum())

      A    B    C    D
0   1.0  2.0  3.0  4.0
1  12.2  2.3  4.3  2.3
2   NaN  3.0  4.0  NaN
A    1
B    0
C    0
D    1
dtype: int64


In [11]:
df_1=df.dropna(axis=0)
print(df_1)
df_2=df.dropna(axis=1)
print(df_2)

      A    B    C    D
0   1.0  2.0  3.0  4.0
1  12.2  2.3  4.3  2.3
     B    C
0  2.0  3.0
1  2.3  4.3
2  3.0  4.0


In [12]:
df_3=df.dropna(how='all')
print(df_3)
df_4=df.dropna(subset=['C'])
print(df_4)

      A    B    C    D
0   1.0  2.0  3.0  4.0
1  12.2  2.3  4.3  2.3
2   NaN  3.0  4.0  NaN
      A    B    C    D
0   1.0  2.0  3.0  4.0
1  12.2  2.3  4.3  2.3
2   NaN  3.0  4.0  NaN


In [13]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputed_data=imputer.fit_transform(df.values)
print(imputed_data)

[[ 1.    2.    3.    4.  ]
 [12.2   2.3   4.3   2.3 ]
 [ 6.6   3.    4.    3.15]]


In [14]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputed_data=imputer.fit_transform(df.values)
print(imputed_data)

[[ 1.    2.    3.    4.  ]
 [12.2   2.3   4.3   2.3 ]
 [ 6.6   3.    4.    3.15]]


In [15]:
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
imputed_data=imputer.fit_transform(df.values)
print(imputed_data)

[[ 1.    2.    3.    4.  ]
 [12.2   2.3   4.3   2.3 ]
 [ 6.6   3.    4.    3.15]]


In [16]:
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputed_data=imputer.fit_transform(df.values)
print(imputed_data)

[[ 1.   2.   3.   4. ]
 [12.2  2.3  4.3  2.3]
 [ 1.   3.   4.   2.3]]
